# Generated by Django 5.2.6 on 2025-09-25 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1, message='El contenido no pude estar vacio')]),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, message='El titulo no pude estar vacio')]),
        ),
    ]
